export const STRIPE_PLAN = {
  ONE_MONTH: "test42",
  SIX_MONTH: "test42"
};

export const ROLE = {
  OWNER: "OWNER",
  OFFICE_INSTRUCTOR: "OFFICE_INSTRUCTOR",
  OFFICE: "OFFICE",
  INSTRUCTOR: "INSTRUCTOR",
  MEMBER: "MEMBER"
};

export const MODAL_SIZE = {
  SMALL: "SMALL",
  MEDIUM: "MEDIUM",
  BIG: "BIG"
};
