// Core
export const SET_ME = "SET_ME";
export const UPDATE_ME_BY_PROFILE = "UPDATE_ME_BY_PROFILE";
export const SET_MEMBER_ME = "SET_MEMBER_ME";

// Sign
export const SET_USER = "SET_USER";

// Settings
export const SET_ORGANIZATION_OWNERED = "SET_ORGANIZATION_OWNERED";

// Organization
export const SET_ORGANIZATION = "SET_ORGANIZATION";
export const EDIT_ORGANIZATION = "EDIT_ORGANIZATION";
export const CHANGE_MEMBER_ROLE = "CHANGE_MEMBER_ROLE";
export const ADD_MEMBER = "ADD_MEMBER";
export const REMOVE_MEMBER = "REMOVE_MEMBER";
export const SET_TYPE_SESSIONS = "SET_TYPE_SESSIONS";
export const ADD_TYPE_SESSION = "ADD_TYPE_SESSION";
export const EDIT_TYPE_SESSION = "EDIT_TYPE_SESSION";
